sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - npm run report-coverage
branches:
  only:
    - master
